site_name: Testcontainers for .NET
repo_name: testcontainers-dotnet
repo_url: https://github.com/testcontainers/testcontainers-dotnet
theme:
  name: material
  palette:
    scheme: testcontainers
  font:
    text: Roboto
    code: Roboto Mono
  logo: logo.svg
  favicon: favicon.ico
extra_css:
  - css/extra.css
plugins:
    - search
    - codeinclude
    - markdownextradata
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
    - Home: index.md
    - Configuration: custom_configuration/index.md
    - Examples:
          - examples/postgres.md
          - examples/nginx.md
edit_uri: edit/develop/docs/
